# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: aiecg
    steps:
      # 1. Set the number of the run
      - task: PowerShell@2
        displayName: Update Run Number
        inputs:
          targetType: 'inline'
          script: '$id = "$(Build.BuildId)"; $date = Get-Date -Format "yyyy.MMdd"; Write-Host "##vso[build.updatebuildnumber]$date.$id"'

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true
          architecture: 'x64'
      
      - task: CmdLine@2
        displayName: Prepare environment
        inputs:
          script: | 
            mkdir -p dataset/ECG/mitdb && rsync -Cavz physionet.org::mitdb dataset/ECG/mitdb
            mkdir -p dataset/ECG/incartdb && rsync -Cavz physionet.org::mitdb dataset/ECG/incartdb

      - task: CmdLine@2
        displayName: Install requirements
        inputs:
          script: | 
            pip install --no-cache-dir -r src/requirements.txt

      - task: PythonScript@0
        inputs:
          scriptSource: 'filePath'
          scriptPath: 'src/main_script.py'
